/**
 * Launcher script templates.
 *
 * @module linuxify/launcher/templates
 *
 * Each function in this module renders a complete POSIX shell-script body
 * for one of the three launcher variants documented in
 * `docs/06-launcher/launcher-architecture.md` §11. The output is a string
 * that the generator writes verbatim to `$PREFIX/bin/<launcherName>` and
 * marks executable (mode 0755).
 *
 * Design constraints:
 *
 *   - **Shebang.** Every launcher begins with `#!/data/data/com.termux/files/usr/bin/sh`
 *     (POSIX sh, not bash). This is deliberate — the launcher must work
 *     regardless of the user's interactive shell (zsh, fish, bash) and `dash`
 *     (Termux's `sh`) has the fastest startup of any POSIX shell on Android
 *     (see `docs/06-launcher/launcher-architecture.md` §2).
 *
 *   - **Header signature.** Every Linuxify launcher carries the comment
 *     `# Auto-generated by Linuxify` in its first few lines. The generator's
 *     `list()` method scans `$PREFIX/bin/` for this signature to enumerate
 *     Linuxify-managed launchers. Removing or rewording this line would make
 *     a launcher invisible to `linuxify repair launchers --dry-run`.
 *
 *   - **`Variant:` header.** All three templates include a `# Variant: <v>`
 *     line so `list()` can report the variant without re-rendering the
 *     template.
 *
 *   - **Argument forwarding.** All templates end with `"$@"` to forward
 *     arguments verbatim, preserving spaces, quotes, and special characters.
 *     This is the standard POSIX idiom.
 *
 *   - **`exec`.** All templates `exec` into the next process so the launcher
 *     shell is replaced (not left lingering as a parent). This keeps the
 *     process tree flat and signal propagation natural (Ctrl-C reaches the
 *     binary directly; see §8 of the launcher-architecture doc).
 *
 * @packageDocumentation
 */

import { LauncherError } from '../utils/errors.js';

import type { LauncherSpec } from './types.js';

/**
 * The Termux `sh` shebang. Hard-coded (not derived from `getTermuxPrefix()`)
 * because:
 *
 *   1. The shebang must be an absolute path, and on Termux `$PREFIX/bin/sh`
 *      is always `/data/data/com.termux/files/usr/bin/sh`.
 *   2. Outside Termux (e.g. in tests on Linux), the shebang points at a
 *      nonexistent path — but the launcher file is never executed on the
 *      dev machine; it is only ever shipped to Termux. Hard-coding keeps
 *      the rendered template deterministic and easy to diff.
 */
export const LAUNCHER_SHEBANG = '#!/data/data/com.termux/files/usr/bin/sh';

/**
 * The substring `list()` looks for to identify Linuxify-managed launchers.
 * Every template includes this exact phrase in a comment header.
 */
export const LINUXIFY_HEADER_SIGNATURE = 'Auto-generated by Linuxify';

/**
 * Render the standard launcher variant. This is the default and the most
 * common variant (~95% of packages). The resulting script `exec`s into
 * `linuxify run <pkg> -- "$@"`, which performs the eight-step proot-entry
 * dance documented in `docs/06-launcher/launcher-architecture.md` §4.
 *
 * @param spec - The launcher specification.
 * @returns The complete shell-script body, ending in a trailing newline.
 *
 * @example
 *   const body = standardTemplate({
 *     packageName: 'cline',
 *     launcherName: 'cline',
 *     distro: 'ubuntu',
 *     variant: 'standard',
 *   });
 *   // body starts with '#!/data/data/com.termux/files/usr/bin/sh'
 *   // body contains 'LINUXIFY_PKG="cline"'
 *   // body ends with 'exec linuxify run "$LINUXIFY_PKG" -- "$@"\n'
 */
export function standardTemplate(spec: LauncherSpec): string {
  return [
    LAUNCHER_SHEBANG,
    `# Auto-generated by Linuxify. Do not edit.`,
    `# Package: ${spec.packageName}`,
    `# Distro: ${spec.distro}`,
    `# Variant: standard`,
    `LINUXIFY_PKG="${spec.packageName}"`,
    `LINUXIFY_DISTRO="${spec.distro}"`,
    `exec linuxify run "$LINUXIFY_PKG" -- "$@"`,
    ``,
  ].join('\n');
}

/**
 * Render the direct launcher variant. This variant bypasses `linuxify run`
 * entirely and execs `proot-distro login` directly, skipping preflight
 * checks, env merging, and CWD binding. Used for performance-critical
 * trusted tools where the ~50–100 ms launcher overhead is unacceptable.
 *
 * Note: the direct variant is distro-specific. If the user switches distros,
 * direct launchers point at the wrong distro's binary and must be regenerated
 * with `linuxify repair launchers`. The package YAML must declare
 * `launcher: direct` explicitly to opt in.
 *
 * @param spec - The launcher specification.
 * @param binaryPath - Absolute path (inside the proot rootfs) of the binary
 *   to exec. Example: `/home/linuxify/.local/bin/cline`.
 * @returns The complete shell-script body, ending in a trailing newline.
 *
 * @example
 *   const body = directTemplate(spec, '/home/linuxify/.local/bin/cline');
 *   // body contains 'exec proot-distro login ubuntu --user linuxify -- /home/linuxify/.local/bin/cline "$@"'
 */
export function directTemplate(spec: LauncherSpec, binaryPath: string): string {
  if (!binaryPath || binaryPath.trim() === '') {
    throw new LauncherError(
      `direct launcher variant requires a non-empty binaryPath (package: ${spec.packageName})`,
      { code: 'DIRECT_BINARY_PATH_MISSING', details: { packageName: spec.packageName } },
    );
  }
  return [
    LAUNCHER_SHEBANG,
    `# Auto-generated by Linuxify (direct variant). Do not edit.`,
    `# Package: ${spec.packageName}`,
    `# Distro: ${spec.distro}`,
    `# Variant: direct`,
    `exec proot-distro login ${spec.distro} --user linuxify -- ${binaryPath} "$@"`,
    ``,
  ].join('\n');
}

/**
 * Render the custom launcher variant. The user provides a script body
 * via `spec.customScript`; Linuxify prepends a header identifying the file
 * as auto-generated and recording the package/distro/variant for `list()`.
 *
 * If the user's script starts with a `#!` shebang, the header is inserted
 * *after* the shebang line (so the user's chosen interpreter is preserved).
 * Otherwise, the standard Termux sh shebang is prepended. This guarantees
 * the resulting file is always a valid executable script regardless of
 * whether the user remembered to include a shebang.
 *
 * @param spec - The launcher specification. `spec.customScript` must be a
 *   non-empty string.
 * @returns The complete shell-script body, ending in a trailing newline.
 * @throws {LauncherError} with code `E_LAUNCHER_CUSTOM_SCRIPT_MISSING` if
 *   `spec.customScript` is missing, empty, or whitespace-only.
 *
 * @example
 *   const body = customTemplate({
 *     packageName: 'mytool',
 *     launcherName: 'mytool',
 *     distro: 'ubuntu',
 *     variant: 'custom',
 *     customScript: '#!/bin/bash\necho hello\nexec linuxify run mytool -- "$@"',
 *   });
 *   // body starts with '#!/bin/bash' (user's shebang preserved)
 *   // body then has '# Auto-generated by Linuxify (custom variant). Do not edit.'
 *   // body ends with 'exec linuxify run mytool -- "$@"\n'
 */
export function customTemplate(spec: LauncherSpec): string {
  if (!spec.customScript || spec.customScript.trim() === '') {
    throw new LauncherError(
      `custom launcher variant requires spec.customScript to be a non-empty script (package: ${spec.packageName})`,
      {
        code: 'CUSTOM_SCRIPT_MISSING',
        details: { packageName: spec.packageName, launcherName: spec.launcherName },
      },
    );
  }

  const headerLines: string[] = [
    `# Auto-generated by Linuxify (custom variant). Do not edit.`,
    `# Package: ${spec.packageName}`,
    `# Distro: ${spec.distro}`,
    `# Variant: custom`,
    `# --- begin user-provided script ---`,
  ];

  const script = spec.customScript;

  // If the user's script already starts with a shebang, preserve it as the
  // first line and insert our header after. Otherwise, prepend our own
  // shebang.
  if (script.startsWith('#!')) {
    const newlineIdx = script.indexOf('\n');
    const shebang = newlineIdx === -1 ? script : script.slice(0, newlineIdx);
    const rest = newlineIdx === -1 ? '' : script.slice(newlineIdx + 1);
    const restWithTrailingNewline = rest === '' || rest.endsWith('\n') ? rest : `${rest}\n`;
    return `${shebang}\n${headerLines.join('\n')}\n${restWithTrailingNewline}`;
  }

  const scriptWithTrailingNewline = script.endsWith('\n') ? script : `${script}\n`;
  return `${LAUNCHER_SHEBANG}\n${headerLines.join('\n')}\n${scriptWithTrailingNewline}`;
}
