// src/bootstrap/stages/stage-6-path.ts
//
// Stage 6 — PATH wiring.
//
// Adds `~/.linuxify/bin` to the user's `PATH` in every shell rc file
// Linuxify knows about (`.bashrc`, `.zshrc`, `.profile`, `.bash_profile`),
// using a guarded block so re-running Stage 6 does not duplicate the entry.
// Also creates `~/.linuxify/bin/` and symlinks `~/.linuxify/bin/linuxify`
// to the actual installed binary so that `linuxify` survives a wipe of
// `~/.linuxify/bin` (the symlink can be regenerated by re-running Stage 6).
//
// See docs/05-bootstrap/bootstrap-design.md §2 (Stage 6) and
// docs/20-adrs/adr-004-shell-launchers-over-symlinks.md for the launcher
// strategy (Stage 6 only wires `linuxify` itself; per-package launchers are
// created by `linuxify add`).

import { readlink, symlink, unlink } from 'node:fs/promises';
import { homedir } from 'node:os';
import { join } from 'node:path';

import { ensureDir, exists, readFile, writeFile } from '../../utils/fs.js';
import { logger } from '../../utils/log.js';
import { getTermuxPrefix } from '../../utils/process.js';
import type { BootstrapContext, StageResult } from '../types.js';

/**
 * Shell rc files edited by Stage 6, relative to the Termux home directory.
 * Each is created if absent.
 */
export const SHELL_RC_FILES: readonly string[] = [
  '.bashrc',
  '.zshrc',
  '.profile',
] as const;

/** Guard markers wrapping the PATH export block. Re-running is a no-op. */
const GUARD_BEGIN = '# >>> linuxify bootstrap >>>';
const GUARD_END = '# <<< linuxify bootstrap <<<';

/** The PATH export block written into each rc file. */
const PATH_BLOCK = [
  GUARD_BEGIN,
  '# Added by `linuxify init` — do not edit between the guard markers.',
  'export PATH="$HOME/.linuxify/bin:$PATH"',
  GUARD_END,
  '',
].join('\n');

/**
 * Bootstrap Stage 6: PATH wiring.
 *
 * For each file in {@link SHELL_RC_FILES}:
 *  1. Ensure it exists (touch).
 *  2. If the guard markers are already present, leave the file alone
 *     (idempotency).
 *  3. Otherwise, append the {@link PATH_BLOCK} to the file.
 *
 * Additionally:
 *  - Creates `~/.linuxify/bin/` if missing.
 *  - Symlinks `~/.linuxify/bin/linuxify` to the actual installed binary
 *    (`$PREFIX/bin/linuxify` if installed via `pkg`, or `process.argv[1]`
 *    as a fallback).
 *
 * @param ctx - Bootstrap context. Uses `ctx.linuxifyHome` for the bin path.
 */
export async function stage6Path(ctx: BootstrapContext): Promise<StageResult> {
  const start = Date.now();

  try {
    const home = homedir();
    const binDir = join(ctx.linuxifyHome, 'bin');
    await ensureDir(binDir);

    const editedFiles: string[] = [];
    const skippedFiles: string[] = [];

    for (const rcName of SHELL_RC_FILES) {
      const rcPath = join(home, rcName);
      const result = await ensurePathBlock(rcPath);
      if (result.edited) {
        editedFiles.push(rcPath);
      } else {
        skippedFiles.push(rcPath);
      }
    }

    // Ensure ~/.bash_profile exists and sources ~/.bashrc (common Termux
    // setup; login shells read .bash_profile, not .bashrc).
    const bashProfilePath = join(home, '.bash_profile');
    if (!(await exists(bashProfilePath))) {
      await writeFile(
        bashProfilePath,
        [
          '# ~/.bash_profile — created by Linuxify bootstrap Stage 6.',
          '# Login shells read this file; we delegate to ~/.bashrc so the',
          '# linuxify PATH export is honoured in both interactive and login',
          '# shells.',
          'if [ -f "$HOME/.bashrc" ]; then',
          '  . "$HOME/.bashrc"',
          'fi',
          '',
        ].join('\n'),
      );
      editedFiles.push(bashProfilePath);
    } else {
      skippedFiles.push(bashProfilePath);
    }

    // Symlink ~/.linuxify/bin/linuxify → actual binary.
    const linkResult = await ensureLinuxifySymlink(binDir);

    return {
      success: true,
      durationMs: Date.now() - start,
      details: {
        binDir,
        editedFiles,
        skippedFiles,
        symlinkTarget: linkResult.target,
        symlinkCreated: linkResult.created,
      },
    };
  } catch (e) {
    return {
      success: false,
      durationMs: Date.now() - start,
      error: `Stage 6 threw: ${(e as Error).message}`,
      details: { name: (e as Error).name },
    };
  }
}

/**
 * Ensure the {@link PATH_BLOCK} is present in `rcPath`. Creates the file if
 * it does not exist. If the guard markers are already present, leaves the
 * file untouched (idempotency).
 *
 * @returns `{ edited: true }` if the file was created or modified,
 *   `{ edited: false }` if the guard was already present.
 */
async function ensurePathBlock(rcPath: string): Promise<{ edited: boolean }> {
  let existing = '';
  if (await exists(rcPath)) {
    existing = await readFile(rcPath);
  }
  if (existing.includes(GUARD_BEGIN) && existing.includes(GUARD_END)) {
    return { edited: false };
  }
  const next = existing.length > 0 && !existing.endsWith('\n')
    ? `${existing}\n\n${PATH_BLOCK}`
    : `${existing}${PATH_BLOCK}`;
  await writeFile(rcPath, next);
  logger.info('stage 6: wrote PATH block', { path: rcPath });
  return { edited: true };
}

/**
 * Ensure `~/.linuxify/bin/linuxify` points at the real binary. If the
 * symlink already exists and points to a valid target, leave it alone;
 * otherwise (re-)create it.
 *
 * The target is resolved in this order:
 *  1. `$PREFIX/bin/linuxify` — present when Linuxify was installed via
 *     `pkg install linuxify` or `npm install -g linuxify` inside Termux.
 *  2. `process.argv[1]` — the currently executing script (works when
 *     Linuxify is run directly via `node /path/to/cli/index.js`).
 *
 * @returns `{ target, created }` where `created` is true if a new symlink
 *   was made (or an existing broken one was replaced).
 */
async function ensureLinuxifySymlink(
  binDir: string,
): Promise<{ target: string | null; created: boolean }> {
  const linkPath = join(binDir, 'linuxify');
  const prefix = getTermuxPrefix();
  const candidates = [join(prefix, 'bin', 'linuxify'), process.argv[1]].filter(
    (s): s is string => typeof s === 'string' && s.length > 0,
  );

  let target: string | null = null;
  for (const candidate of candidates) {
    if (await exists(candidate)) {
      target = candidate;
      break;
    }
  }

  if (!target) {
    logger.warn('stage 6: could not locate linuxify binary to symlink', {
      candidates,
    });
    return { target: null, created: false };
  }

  // If the existing symlink already points to the same target, no-op.
  if (await exists(linkPath)) {
    try {
      const current = await readlink(linkPath);
      if (current === target) {
        return { target, created: false };
      }
    } catch {
      // Not a symlink (or broken) — fall through and replace.
    }
    await unlink(linkPath).catch(() => undefined);
  }

  await symlink(target, linkPath);
  logger.info('stage 6: created linuxify symlink', { linkPath, target });
  return { target, created: true };
}
