/**
 * Unit tests for `src/launcher/templates.ts`.
 *
 * Verifies that each template function:
 *   - Renders the Termux sh shebang (or preserves a user-provided shebang
 *     for the custom variant).
 *   - Includes the Linuxify header signature so `list()` can find it.
 *   - Substitutes spec variables (packageName, distro, binaryPath) correctly.
 *   - Ends with the correct exec line for its variant.
 *   - Throws on missing required variant-specific fields.
 *
 * These tests are pure: they call the template functions directly without
 * touching the filesystem. The generator's I/O behavior is covered by
 * `generator.test.ts`.
 */

import { describe, it, expect } from 'vitest';

import {
  customTemplate,
  directTemplate,
  standardTemplate,
  LAUNCHER_SHEBANG,
  LINUXIFY_HEADER_SIGNATURE,
} from '../../../src/launcher/templates.js';
import { LauncherError } from '../../../src/utils/errors.js';
import type { LauncherSpec } from '../../../src/launcher/types.js';

// ---------------------------------------------------------------------------
// Test fixtures
// ---------------------------------------------------------------------------

/** A standard-variant spec used by most tests. */
const STANDARD_SPEC: LauncherSpec = {
  packageName: 'cline',
  launcherName: 'cline',
  distro: 'ubuntu',
  variant: 'standard',
};

/** A direct-variant spec (without binaryPath — passed separately to the template). */
const DIRECT_SPEC: LauncherSpec = {
  packageName: 'eslint',
  launcherName: 'eslint',
  distro: 'debian',
  variant: 'direct',
};

/** A custom-variant spec with a user-provided script that already has a shebang. */
const CUSTOM_SPEC_WITH_SHEBANG: LauncherSpec = {
  packageName: 'mytool',
  launcherName: 'mytool',
  distro: 'alpine',
  variant: 'custom',
  customScript: '#!/bin/bash\necho "pre"\nexec linuxify run mytool -- "$@"',
};

/** A custom-variant spec with a user-provided script that lacks a shebang. */
const CUSTOM_SPEC_NO_SHEBANG: LauncherSpec = {
  packageName: 'bare',
  launcherName: 'bare',
  distro: 'arch',
  variant: 'custom',
  customScript: 'echo hello\nexec linuxify run bare -- "$@"',
};

// ---------------------------------------------------------------------------
// standardTemplate
// ---------------------------------------------------------------------------

describe('standardTemplate', () => {
  it('starts with the Termux sh shebang', () => {
    const out = standardTemplate(STANDARD_SPEC);
    const firstLine = out.split('\n')[0]!;
    expect(firstLine).toBe(LAUNCHER_SHEBANG);
    expect(firstLine).toBe('#!/data/data/com.termux/files/usr/bin/sh');
  });

  it('includes the Linuxify header signature on the second line', () => {
    const out = standardTemplate(STANDARD_SPEC);
    const lines = out.split('\n');
    expect(lines[1]).toBe('# Auto-generated by Linuxify. Do not edit.');
    expect(out).toContain(LINUXIFY_HEADER_SIGNATURE);
  });

  it('records the package name in the header', () => {
    const out = standardTemplate(STANDARD_SPEC);
    expect(out).toContain('# Package: cline');
  });

  it('records the distro in the header', () => {
    const out = standardTemplate(STANDARD_SPEC);
    expect(out).toContain('# Distro: ubuntu');
  });

  it('records the variant in the header', () => {
    const out = standardTemplate(STANDARD_SPEC);
    expect(out).toContain('# Variant: standard');
  });

  it('substitutes packageName into the LINUXIFY_PKG env var', () => {
    const out = standardTemplate(STANDARD_SPEC);
    expect(out).toContain('LINUXIFY_PKG="cline"');
  });

  it('substitutes distro into the LINUXIFY_DISTRO env var', () => {
    const out = standardTemplate(STANDARD_SPEC);
    expect(out).toContain('LINUXIFY_DISTRO="ubuntu"');
  });

  it('ends with the exec line forwarding arguments verbatim', () => {
    const out = standardTemplate(STANDARD_SPEC);
    expect(out).toContain('exec linuxify run "$LINUXIFY_PKG" -- "$@"');
    // Last non-empty line should be the exec line.
    const lines = out.split('\n').filter((l) => l.length > 0);
    expect(lines[lines.length - 1]).toBe('exec linuxify run "$LINUXIFY_PKG" -- "$@"');
  });

  it('ends with exactly one trailing newline', () => {
    const out = standardTemplate(STANDARD_SPEC);
    expect(out.endsWith('\n')).toBe(true);
    expect(out.endsWith('\n\n')).toBe(false);
  });

  it('substitutes different spec values correctly', () => {
    const spec: LauncherSpec = {
      packageName: 'codex',
      launcherName: 'codex',
      distro: 'debian',
      variant: 'standard',
    };
    const out = standardTemplate(spec);
    expect(out).toContain('# Package: codex');
    expect(out).toContain('# Distro: debian');
    expect(out).toContain('LINUXIFY_PKG="codex"');
    expect(out).toContain('LINUXIFY_DISTRO="debian"');
    // Should NOT contain the previous spec's values.
    expect(out).not.toContain('cline');
    expect(out).not.toContain('ubuntu');
  });

  it('handles package names with hyphens and dots', () => {
    const spec: LauncherSpec = {
      packageName: 'my.tool-kit',
      launcherName: 'my.tool-kit',
      distro: 'ubuntu',
      variant: 'standard',
    };
    const out = standardTemplate(spec);
    expect(out).toContain('LINUXIFY_PKG="my.tool-kit"');
  });
});

// ---------------------------------------------------------------------------
// directTemplate
// ---------------------------------------------------------------------------

describe('directTemplate', () => {
  it('starts with the Termux sh shebang', () => {
    const out = directTemplate(DIRECT_SPEC, '/home/linuxify/.local/bin/eslint');
    expect(out.split('\n')[0]).toBe(LAUNCHER_SHEBANG);
  });

  it('includes the Linuxify header signature', () => {
    const out = directTemplate(DIRECT_SPEC, '/home/linuxify/.local/bin/eslint');
    expect(out).toContain('Auto-generated by Linuxify');
    expect(out).toContain(LINUXIFY_HEADER_SIGNATURE);
  });

  it('records the package name in the header', () => {
    const out = directTemplate(DIRECT_SPEC, '/home/linuxify/.local/bin/eslint');
    expect(out).toContain('# Package: eslint');
  });

  it('records the distro in the header', () => {
    const out = directTemplate(DIRECT_SPEC, '/home/linuxify/.local/bin/eslint');
    expect(out).toContain('# Distro: debian');
  });

  it('records the variant as direct in the header', () => {
    const out = directTemplate(DIRECT_SPEC, '/home/linuxify/.local/bin/eslint');
    expect(out).toContain('# Variant: direct');
  });

  it('does NOT set LINUXIFY_PKG or LINUXIFY_DISTRO env vars (direct bypasses linuxify run)', () => {
    const out = directTemplate(DIRECT_SPEC, '/home/linuxify/.local/bin/eslint');
    expect(out).not.toContain('LINUXIFY_PKG=');
    expect(out).not.toContain('LINUXIFY_DISTRO=');
  });

  it('substitutes distro and binaryPath into the proot-distro login command', () => {
    const out = directTemplate(DIRECT_SPEC, '/home/linuxify/.local/bin/eslint');
    expect(out).toContain(
      'exec proot-distro login debian --user linuxify -- /home/linuxify/.local/bin/eslint "$@"',
    );
  });

  it('uses --user linuxify (the unprivileged user inside the proot)', () => {
    const out = directTemplate(DIRECT_SPEC, '/usr/bin/eslint');
    expect(out).toContain('--user linuxify');
  });

  it('forwards arguments verbatim via "$@"', () => {
    const out = directTemplate(DIRECT_SPEC, '/usr/bin/eslint');
    expect(out).toContain('"$@"');
  });

  it('throws LauncherError(E_LAUNCHER_DIRECT_BINARY_PATH_MISSING) when binaryPath is empty', () => {
    expect(() => directTemplate(DIRECT_SPEC, '')).toThrow(LauncherError);
    expect(() => directTemplate(DIRECT_SPEC, '')).toThrow(/binaryPath/);
  });

  it('throws LauncherError(E_LAUNCHER_DIRECT_BINARY_PATH_MISSING) when binaryPath is whitespace', () => {
    expect(() => directTemplate(DIRECT_SPEC, '   ')).toThrow(LauncherError);
  });

  it('handles binaryPaths with spaces and special characters', () => {
    const out = directTemplate(DIRECT_SPEC, '/home/linuxify/my tools/eslint');
    expect(out).toContain('/home/linuxify/my tools/eslint "$@"');
  });
});

// ---------------------------------------------------------------------------
// customTemplate
// ---------------------------------------------------------------------------

describe('customTemplate', () => {
  it('preserves the user-provided shebang as the first line', () => {
    const out = customTemplate(CUSTOM_SPEC_WITH_SHEBANG);
    expect(out.split('\n')[0]).toBe('#!/bin/bash');
  });

  it('inserts the Linuxify header after the user shebang', () => {
    const out = customTemplate(CUSTOM_SPEC_WITH_SHEBANG);
    const lines = out.split('\n');
    expect(lines[0]).toBe('#!/bin/bash');
    expect(lines[1]).toBe('# Auto-generated by Linuxify (custom variant). Do not edit.');
  });

  it('includes the package name and distro in the header', () => {
    const out = customTemplate(CUSTOM_SPEC_WITH_SHEBANG);
    expect(out).toContain('# Package: mytool');
    expect(out).toContain('# Distro: alpine');
    expect(out).toContain('# Variant: custom');
  });

  it('includes the Linuxify header signature', () => {
    const out = customTemplate(CUSTOM_SPEC_WITH_SHEBANG);
    expect(out).toContain(LINUXIFY_HEADER_SIGNATURE);
  });

  it('preserves the user-provided script body verbatim', () => {
    const out = customTemplate(CUSTOM_SPEC_WITH_SHEBANG);
    expect(out).toContain('echo "pre"');
    expect(out).toContain('exec linuxify run mytool -- "$@"');
  });

  it('prepends the Termux sh shebang when the user script lacks one', () => {
    const out = customTemplate(CUSTOM_SPEC_NO_SHEBANG);
    expect(out.split('\n')[0]).toBe(LAUNCHER_SHEBANG);
    expect(out.split('\n')[0]).toBe('#!/data/data/com.termux/files/usr/bin/sh');
  });

  it('inserts the header after the prepended shebang when the user script lacks one', () => {
    const out = customTemplate(CUSTOM_SPEC_NO_SHEBANG);
    const lines = out.split('\n');
    expect(lines[0]).toBe('#!/data/data/com.termux/files/usr/bin/sh');
    expect(lines[1]).toBe('# Auto-generated by Linuxify (custom variant). Do not edit.');
  });

  it('preserves the user-provided script body when no shebang is present', () => {
    const out = customTemplate(CUSTOM_SPEC_NO_SHEBANG);
    expect(out).toContain('echo hello');
    expect(out).toContain('exec linuxify run bare -- "$@"');
  });

  it('adds a trailing newline if the user script lacks one', () => {
    const spec: LauncherSpec = {
      packageName: 'p',
      launcherName: 'p',
      distro: 'ubuntu',
      variant: 'custom',
      customScript: 'echo hello',
    };
    const out = customTemplate(spec);
    expect(out.endsWith('\n')).toBe(true);
    expect(out.endsWith('\n\n')).toBe(false);
  });

  it('does not add a duplicate trailing newline if the user script already ends with one', () => {
    const spec: LauncherSpec = {
      packageName: 'p',
      launcherName: 'p',
      distro: 'ubuntu',
      variant: 'custom',
      customScript: 'echo hello\n',
    };
    const out = customTemplate(spec);
    expect(out.endsWith('\n')).toBe(true);
    expect(out.endsWith('\n\n')).toBe(false);
  });

  it('throws LauncherError(E_LAUNCHER_CUSTOM_SCRIPT_MISSING) when customScript is missing', () => {
    const spec: LauncherSpec = {
      packageName: 'p',
      launcherName: 'p',
      distro: 'ubuntu',
      variant: 'custom',
    };
    expect(() => customTemplate(spec)).toThrow(LauncherError);
    expect(() => customTemplate(spec)).toThrow(/customScript/);
  });

  it('throws LauncherError(E_LAUNCHER_CUSTOM_SCRIPT_MISSING) when customScript is empty', () => {
    const spec: LauncherSpec = {
      packageName: 'p',
      launcherName: 'p',
      distro: 'ubuntu',
      variant: 'custom',
      customScript: '',
    };
    expect(() => customTemplate(spec)).toThrow(LauncherError);
  });

  it('throws LauncherError(E_LAUNCHER_CUSTOM_SCRIPT_MISSING) when customScript is whitespace-only', () => {
    const spec: LauncherSpec = {
      packageName: 'p',
      launcherName: 'p',
      distro: 'ubuntu',
      variant: 'custom',
      customScript: '   \n\t  ',
    };
    expect(() => customTemplate(spec)).toThrow(LauncherError);
  });

  it('includes a "begin user-provided script" separator line', () => {
    const out = customTemplate(CUSTOM_SPEC_WITH_SHEBANG);
    expect(out).toContain('# --- begin user-provided script ---');
  });

  it('handles a user script that is only a shebang line (no body)', () => {
    const spec: LauncherSpec = {
      packageName: 'p',
      launcherName: 'p',
      distro: 'ubuntu',
      variant: 'custom',
      customScript: '#!/bin/sh',
    };
    const out = customTemplate(spec);
    const lines = out.split('\n');
    expect(lines[0]).toBe('#!/bin/sh');
    expect(lines[1]).toBe('# Auto-generated by Linuxify (custom variant). Do not edit.');
  });
});

// ---------------------------------------------------------------------------
// Cross-variant invariants
// ---------------------------------------------------------------------------

describe('cross-variant invariants', () => {
  it('all three variants include the Linuxify header signature', () => {
    const std = standardTemplate(STANDARD_SPEC);
    const dir = directTemplate(DIRECT_SPEC, '/usr/bin/eslint');
    const cus = customTemplate(CUSTOM_SPEC_WITH_SHEBANG);
    expect(std).toContain(LINUXIFY_HEADER_SIGNATURE);
    expect(dir).toContain(LINUXIFY_HEADER_SIGNATURE);
    expect(cus).toContain(LINUXIFY_HEADER_SIGNATURE);
  });

  it('all three variants end with exactly one trailing newline', () => {
    const std = standardTemplate(STANDARD_SPEC);
    const dir = directTemplate(DIRECT_SPEC, '/usr/bin/eslint');
    const cus = customTemplate(CUSTOM_SPEC_WITH_SHEBANG);
    for (const out of [std, dir, cus]) {
      expect(out.endsWith('\n')).toBe(true);
      expect(out.endsWith('\n\n')).toBe(false);
    }
  });

  it('all three variants forward arguments via "$@"', () => {
    const std = standardTemplate(STANDARD_SPEC);
    const dir = directTemplate(DIRECT_SPEC, '/usr/bin/eslint');
    const cus = customTemplate(CUSTOM_SPEC_WITH_SHEBANG);
    expect(std).toContain('"$@"');
    expect(dir).toContain('"$@"');
    expect(cus).toContain('"$@"');
  });
});
