/**
 * Diagnosis engine — matches doctor results to repair plans.
 *
 * @module linuxify/diagnosis/engine
 */

import { logger } from '../utils/log.js';
import type { DoctorReport, DoctorResult } from '../doctor/types.js';
import type { Report } from '../report/index.js';
import { getDiagnosisRule } from './rules.js';
import { assessRepairSafety } from './safety.js';

/**
 * Risk level of a proposed repair.
 *
 * - `safe` — no destructive operations, reversible (e.g., regenerate launchers)
 * - `moderate` — modifies state but recoverable (e.g., reinstall a package)
 * - `risky` — modifies distro rootfs or removes user data (e.g., distro reset)
 * - `destructive` — irreversible; refuses to auto-apply (e.g., rm -rf ~/.linuxify)
 */
export type RiskLevel = 'safe' | 'moderate' | 'risky' | 'destructive';

/**
 * A single piece of evidence supporting a diagnosis. Maps 1:1 to a doctor
 * check result, with an optional `interpretation` explaining what the value
 * means in context.
 */
export interface DiagnosisEvidence {
  checkId: string;
  checkName: string;
  status: string;
  message: string;
  interpretation?: string;
}

/**
 * A single step in a repair plan. Steps run sequentially; if any step fails,
 * the plan aborts.
 */
export interface RepairStep {
  /** Human-readable description of what this step does. */
  description: string;
  /** The shell command to execute. Empty for "manual" steps. */
  command?: string;
  /** Whether this step modifies state (vs. just checking). */
  modifiesState: boolean;
  /** Estimated duration in seconds. */
  estimatedSeconds: number;
}

/**
 * A complete repair plan. Generated by a {@link DiagnosisRule} and validated
 * by the safety filter before presentation to the user.
 */
export interface RepairPlan {
  /** Short summary of the repair (one line). */
  summary: string;
  /** Detailed explanation of what the repair will do. */
  description: string;
  /** Ordered steps. */
  steps: RepairStep[];
  /** Overall risk level (max of step risks). */
  risk: RiskLevel;
  /** What this repair will fix. */
  fixes: string[];
  /** What this repair will NOT fix (so user knows limits). */
  doesNotFix: string[];
  /** Whether this repair requires network access. */
  requiresNetwork: boolean;
  /** Estimated total duration in seconds. */
  estimatedDurationSeconds: number;
}

/**
 * A complete diagnosis for a single problem. One diagnosis per failing check
 * (or per cluster of related failing checks).
 */
export interface Diagnosis {
  /** Stable ID for this diagnosis type, e.g., `path.linuxify_bin.missing`. */
  id: string;
  /** One-line summary, e.g., "PATH is not configured for Linuxify". */
  title: string;
  /** WHAT went wrong, plain English, 1-3 sentences. */
  what: string;
  /** WHY it likely went wrong, plain English, 1-3 sentences. */
  why: string;
  /** Evidence from doctor results. */
  evidence: DiagnosisEvidence[];
  /** Proposed repair plan (if any). May be null if no safe repair exists. */
  repair: RepairPlan | null;
  /** Alternative repairs, lower priority. */
  alternatives: RepairPlan[];
  /** Docs URL for more context. */
  docsUrl?: string;
  /** Confidence 0-1. Rules can express uncertainty. */
  confidence: number;
}

/**
 * Run diagnosis against a doctor report (and optional environment report for
 * extra context). Returns at most one diagnosis per failing check, sorted by
 * impact (fail > missing > warn) and then by check ID.
 *
 * @returns Array of diagnoses. Empty if no failures.
 */
export async function diagnose(
  doctorReport: DoctorReport,
  envReport?: Report,
): Promise<Diagnosis[]> {
  const failing = doctorReport.results.filter(
    (r) => r.status === 'fail' || r.status === 'missing',
  );
  const warnings = doctorReport.results.filter((r) => r.status === 'warn');

  const diagnoses: Diagnosis[] = [];

  for (const result of failing) {
    const rule = getDiagnosisRule(result.id);
    if (rule) {
      try {
        const diagnosis = await rule.diagnose(result, envReport);
        if (diagnosis) diagnoses.push(diagnosis);
      } catch (err) {
        logger.warn(
          { checkId: result.id, err: (err as Error).message },
          'diagnosis rule threw — skipping',
        );
      }
    } else {
      // No rule for this check — generate a generic diagnosis
      diagnoses.push(genericDiagnosis(result));
    }
  }

  // Also diagnose warnings (lower priority)
  for (const result of warnings) {
    const rule = getDiagnosisRule(result.id);
    if (rule) {
      try {
        const diagnosis = await rule.diagnose(result, envReport);
        if (diagnosis) diagnoses.push(diagnosis);
      } catch {
        // skip
      }
    }
  }

  // Sort: failing first, then warnings, then by check ID
  return diagnoses.sort((a, b) => {
    const aFail = a.evidence.some((e) => e.status === 'fail' || e.status === 'missing');
    const bFail = b.evidence.some((e) => e.status === 'fail' || e.status === 'missing');
    if (aFail !== bFail) return aFail ? -1 : 1;
    return a.id.localeCompare(b.id);
  });
}

/**
 * A rule that maps a doctor check ID to a diagnosis generator.
 */
export interface DiagnosisRule {
  /** Doctor check ID this rule handles, e.g., `path.linuxify_bin`. */
  checkId: string;
  /** Human-readable name of the rule. */
  name: string;
  /**
   * Generate a diagnosis for this check result. Return null if the rule
   * decides not to diagnose (e.g., the failure is expected in this context).
   */
  diagnose: (result: DoctorResult, envReport?: Report) => Promise<Diagnosis | null>;
}

function genericDiagnosis(result: DoctorResult): Diagnosis {
  return {
    id: `${result.id}.generic`,
    title: result.name,
    what: result.message,
    why: 'No specific root-cause hypothesis is available for this check. This is a gap in the diagnosis rules — consider contributing one.',
    evidence: [
      {
        checkId: result.id,
        checkName: result.name,
        status: result.status,
        message: result.message,
      },
    ],
    repair: result.fixCommand
      ? {
          summary: `Run the suggested fix command`,
          description: `Doctor suggests: ${result.fixCommand}`,
          steps: [
            {
              description: result.fixCommand,
              command: result.fixCommand,
              modifiesState: true,
              estimatedSeconds: 10,
            },
          ],
          risk: 'moderate',
          fixes: [result.message],
          doesNotFix: [],
          requiresNetwork: false,
          estimatedDurationSeconds: 10,
        }
      : null,
    alternatives: [],
    docsUrl: result.fixDocs,
    confidence: 0.3,
  };
}

/**
 * Validate a repair plan against the safety filter. Mutates the plan's risk
 * field if the safety filter escalates it.
 */
export function validateRepairPlan(plan: RepairPlan): RepairPlan {
  const assessment = assessRepairSafety(plan);
  if (assessment.escalatedRisk && assessment.effectiveRisk) {
    return { ...plan, risk: assessment.effectiveRisk };
  }
  return plan;
}
